services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
